### ISSUE TITLE
Which annotation software do you think is more suitable for analysis?

### ISSUE THREAD

**Issue by Dx-wmc** [maxgmarin/panqc#2]
Hi, I've read your article on bioRxiv and found it quite beneficial. Having used both Bakta and PGAP, I noticed their results often differ as you mentioned. Based on your analysis, which tool would you recommend as a standard or better choice for Enterobacteriaceae genome annotation and pan-genomic analysis?

**Comment by maxgmarin** [comment]
Hello Dave! I think both annotation pipelines can lead to good results. The most important thing is to be consistent with the pipeline used.

With that said, I would have a slight bias towards using PGAP and then running Panaroo. In my experience PGAP is much harder to install and run on assemblies yourself.

Best of luck! 
- Max

**Comment by Dx-wmc** [comment]
Thank you for your answer, I also hold the same opinion, but the biggest disadvantage of PGAP is the excessively slow running speed.
